version: '3.8'

services:
  jupyter:
    image: ghcr.io/flamers-team/flammers-techchallenge-fase01:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flammers-techchallenge-jupyter
    ports:
      - "8888:8888"
    volumes:
      - .:/workspace
    environment:
      - JUPYTER_ENABLE_LAB=yes
